
print("Welcome to Scrabble!")
print()
print("The basic set up consists of a board, an AI, and you")
print("You and the AI compete against eachother to make words for points with the tiles on the board")
print("There are 100 total letter tiles used to make words in each game and each player 7 in their hand at all times")
print()
print()
print("Game Play:")
print("Each player is assigned 7 random tiles from the bag")
print("The first player combines two or more of his or her letters to form a word and places it on the board to read either across or down with one letter on the center square. Diagonal words are not allowed.")
print("The program automatically counts the score and adds it to the players total, then then played pieces are replaced by random tiles from the bag")
print("Play passes to the next player. The next player, adds one or more letters to those already played to form new words. All letters played on a turn must be placed in one row across or down the board, to form at least one complete word. If, at the same time, they touch others letters in adjacent rows, those must also form complete words, crossword fashion, with all such letters. The player gets full credit for all words formed or modified on his or her turn.")
print()
print()
print("New words may be formed by:")
print("Adding one or more letters to a word or letters already on the board.")
print("Placing a word at right angles to a word already on the board. The new word must use one of the letters already on the board or must add a letter to it.")
print("Placing a complete word parallel to a word already played so that adjacent letters also form complete words.")
print("No tile may be shifted or replaced after it has been played and scored.")
print()
print("Blanks: The two blank tiles may be used as any letters. When playing a blank, you must state which letter it represents. It remains that letter for the rest of the game.")
print("You may use a turn to exchange all, some, or none of the letters. To do this, place your discarded letter(s) facedown. Draw the same number of letters from the pool, then mix your discarded letter(s) into the pool. This ends your turn.")
print("The game ends when all letters have been drawn and one player uses his or her last letter; or when all possible plays have been made.")